### ISSUE TITLE
Question about Required Environment for the Model

### ISSUE THREAD

**Issue by leem18** [samsartor/content_aware_tiles#1]
I appreciate so much for sharing codes for this awesome research and accomplishment. While studying development of texture synthesis, I found your journal was one of the most appropriate models to be further studied and referred to. But I am leaving some comments here to request if you can provide some more information about this model.

While studying more deeply about your code and attempting to run the code on my environment, I could find that some of the libraries and packages used in your code are not compatible with Python 3(e.g. Python 3.8 or more recent versions). For instance, in my enviroment (Python 3.10.11), I had to change "image_prompt: str | None = None" into "image_prompt: Optional[str] = None" for the first few lines in "generate_tiles.py" file. Also, I had to download "memcacheConstatns.py" file from https://github.com/couchbase/ep-engine/blob/master/management/memcacheConstants.py to run the code properly.

Also, I attempted to run the Img2Tile process by putting an image input, but it did not work out well. I used 256x256 images; however, it seems that certain format for the image input. 

I believe those types of problems may occurred because I tried to run it on my terminal but not Comfy.UI. But still, can you provide any prerequisites/requirements for the environment or Dockerfile, if exist? Also, can you inform proper size, resolution, or ratio of the image input to take the Img2Tile process?

Thank you!

**Comment by samsartor** [comment]
Thanks for trying our work!

The terminal version is actually a tiny bit more reliable than the ComfyUI version in my experience (something is weird in how comfy scales inpaint masks which I haven't tracked down) so I'd recommend using it anyway, especially if you're happy hacking on the code.

The Img2Tile process generally benefits from --cut_length in the range of ½-¼ the size of the input image, which is definitely worth adding to the docs. To avoid up/downscaling that usually means an input image in the 512-1024px range. The idea is you want boundary cuts randomly spread out in the input, to get a diverse set of wang/dual tiles. But `--cut_length=fill` (or equivalently --cut_length=256 with a 256px input) may be fine if you are only generating a singe tile. More specifically, what is the issue you are running into?

The `str | None` syntax was introduced by PEP 604 and _should be_ available starting in 3.10 (https://docs.python.org/3/whatsnew/3.10.html). You might double-check your venv/conda environment. The memcacheConstants.py is also really bizarre. AFAIK nothing in our code or the dependencies does memcache stuff. Can you share the full error you got there?

Also, adding a Dockerfile is a great idea, thanks!

**Comment by leem18** [comment]
Thanks for your kind reply!

I also appreciate you for positively considering to share Dockerfile.

I can now understand how `--cut_length` works. So I believe that part is not a matter anymore. Thanks for your explanation.

Also, unfortunately for the `str | None` syntax and memcache part, I have not tracked the errors and already fixed it by adding memcache stuffs and changing some small elements. So I cannot provide the full error. But I will try to run your model from scratch based on the information you just provided. But still thanks for asking.

In addition, I think your novel approach to exterior boundary conditions for tileability is very impressive.  Recently, I have been researching about repeatable, seamless, and tileable texture synthesis and and think that tileability is still a very complicated issue. While surveying, I could find that you attend the SIGGRAPH Asia 2024. I also visit SIGGGRAPH Asia next week as a member of Giantstep Inc. In that regard, if your time allows, do you mind having a short coffee chat with me (and possibly one or two of our members) to talk more about your research next week at Tokyo, Japan?

I will look forward to hearing from you.
Thank you!

**Comment by samsartor** [comment]
Yah, I'd love to meet up in Tokyo. I sent you an email. And let me know if there are any other fixes/additions I should consider.
